twig:
    file_name_pattern: '*.twig'
    globals:
        breadcrumb_trail: '@APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail'

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig']
    
