vich_uploader:
    db_driver: orm

    mappings:
        categories_image:
            uri_prefix: /images/categories
            upload_destination: "%kernel.project_dir%/public/images/categories"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        velos_image:
            uri_prefix: /images/velos
            upload_destination: "%kernel.project_dir%/public/images/velos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    metadata:
        type: attribute